### ISSUE TITLE
PUT /bib/<id> is not idempotic

### ISSUE THREAD

**Issue by ghost** [NatLibFi/voyager-http-api#5]
Calling **PUT /bib/\<id\>** fails if called with the same data multiple times. Voyager requires MARC data to contain the latest timestamp. For this reason updating resources in Voyager cannot be done idempotically.

## Suggested implementation
Ditch **PUT** on **/bib/\<id\>** in favor of **POST**. POSTing on the resource should respond with status code **200** (On success) and return the updated data in the body.

**Comment by petuomin** [comment]
I would like to keep the PUT since it's very common to map PUT to update. Maybe the best solution is to keep it as is. Often the only interesting part is that the update has been applied successfully. In case the newly updated record is needed, the client is expected to fetch it and update the record in user's view.

**Comment by ghost** [comment]
The method will be kept as PUT
